# IMPORTACIONES Y CONFIGURACIÓN CSV

In [2]:
#importamos librerías 

import pandas as pd
import numpy as np

import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
#importamos librerías para el preprocesamiento de datos

import warnings 
warnings.filterwarnings('ignore', category=FutureWarning)

In [4]:
#configuramos pandas para mostrar todas las columnas del dataframe

pd.set_option('display.max_columns', None)

# FASE 1 - EXPLORACIÓN Y LIMPIEZA 

# 1. EXPLORACIÓN INICIAL

# LECTURA DATASET

In [7]:
#cargamos el primer dataset
df_1 = pd.read_csv("files/Customer Flight Activity.csv")
#mostramos las cinco primeras filas del dataframe 
df_1.head(5)

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
0,100018,2017,1,3,0,3,1521,152.0,0,0
1,100102,2017,1,10,4,14,2030,203.0,0,0
2,100140,2017,1,6,0,6,1200,120.0,0,0
3,100214,2017,1,0,0,0,0,0.0,0,0
4,100272,2017,1,0,0,0,0,0.0,0,0

In [8]:
#cargamos el segundo dataset
df_2 = pd.read_csv("files/Customer Loyalty History.csv")
#mostramos las cinco primeras filas del dataframe
df_2.head(5)

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
0,480934,Canada,Ontario,Toronto,M2Z 4K1,Female,Bachelor,83236.0,Married,Star,3839.14,Standard,2016,2,NaN,NaN
1,549612,Canada,Alberta,Edmonton,T3G 6Y6,Male,College,NaN,Divorced,Star,3839.61,Standard,2016,3,NaN,NaN
2,429460,Canada,British Columbia,Vancouver,V6E 3D9,Male,College,NaN,Single,Star,3839.75,Standard,2014,7,2018.0,1.0
3,608370,Canada,Ontario,Toronto,P1W 1K4,Male,College,NaN,Single,Star,3839.75,Standard,2013,2,NaN,NaN
4,530508,Canada,Quebec,Hull,J8Y 3Z5,Male,Bachelor,103495.0,Married,Star,3842.79,Standard,2014,10,NaN,NaN

# MÉTODOS PARA FAMILIARIZARNOS CON LOS CSVs

In [13]:
#El método sample nos devuelve una muestra aleatoria de filas del dataframe
df_1.sample(5)

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
325013,308891,2018,8,16,8,24,2712,271.0,0,0
71394,302827,2017,5,0,0,0,0,0.0,0,0
32709,942194,2017,2,0,0,0,0,0.0,0,0
44792,804137,2018,9,10,5,15,3570,357.0,404,33
101757,118628,2017,7,0,0,0,0,0.0,0,0

In [ ]:
#El método info nos devuelve un resumen de la información del dataframe, incluyendo el número de filas, el número de columnas, 
#el tipo de datos de cada columna y el número de valores no nulos en cada columna.
#Vemos que hay 10 columnas, 9 de tipo int64 y 1 de tipo float64. 
df_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 405624 entries, 0 to 405623
Data columns (total 10 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Loyalty Number               405624 non-null  int64
 1   Year                         405624 non-null  int64
 2   Month                        405624 non-null  int64
 3   Flights Booked               405624 non-null  int64
 4   Flights with Companions      405624 non-null  int64
 5   Total Flights                405624 non-null  int64
 6   Distance                     405624 non-null  int64
 7   Points Accumulated           405624 non-null  float64
 8   Points Redeemed              405624 non-null  int64
 9   Dollar Cost Points Redeemed  405624 non-null  int64
dtypes: float64(1), int64(9)
memory usage: 30.9 MB

In [ ]:
#Utilizamos el método describe para obtener un resumen estadístico de las columnas numéricas del df_1 (todas son numéricas)
df_1.describe()

,Loyalty Number,Year,Month,Flights Booked,Flights with Companions,Total Flights,Distance,Points Accumulated,Points Redeemed,Dollar Cost Points Redeemed
count,405624.000000,405624.000000,405624.000000,405624.000000,405624.000000,405624.000000,405624.000000,405624.000000,405624.000000,405624.000000
mean,550037.873084,2017.500000,6.500000,4.115052,1.031805,5.146858,1208.880059,123.692721,30.696872,2.484503
std,258935.286969,0.500001,3.452057,5.225518,2.076869,6.521227,1433.155320,146.599831,125.486049,10.150038
min,100018.000000,2017.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,326961.000000,2017.000000,3.750000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,550834.000000,2017.500000,6.500000,1.000000,0.000000,1.000000,488.000000,50.000000,0.000000,0.000000
75%,772194.000000,2018.000000,9.250000,8.000000,1.000000,10.000000,2336.000000,239.000000,0.000000,0.000000
max,999986.000000,2018.000000,12.000000,21.000000,11.000000,32.000000,6293.000000,676.500000,876.000000,71.000000

In [10]:
#El método shape nos devuelve el número de filas y columnas del df_1
print(f"El número de filas que tenemos es {df_1.shape[0]}, y el número de columnas es {df_1.shape[1]}")

El número de filas que tenemos es 405624, y el número de columnas es 10

In [ ]:
#El método duplicated nos devuelve un booleano indicando si cada fila es un duplicado de una fila anterior. El método sum nos devuelve el número total de filas duplicadas.
df_1.duplicated().sum()

np.int64(1864)

In [ ]:
#El método duplicated con el parámetro subset nos permite especificar una columna o un conjunto de columnas para identificar filas duplicadas. 
#En este caso, estamos buscando filas duplicadas basándonos en la columna "Loyalty Number". 
df_1.duplicated(subset="Loyalty Number", keep=False).sum()

np.int64(405624)

In [ ]:
#Estos duplicados son un error de inserción? se pueden eliminar?
#Devuelve una lista de todas las filas que están repetidas, mostrando el contenido de la fila y una columna al lado que indica el número total de repeticiones

df_1[df_1.duplicated(keep=False)].value_counts()

Loyalty Number  Year  Month  Flights Booked  Flights with Companions  Total Flights  Distance  Points Accumulated  Points Redeemed  Dollar Cost Points Redeemed
678205          2017  1      0               0                        0              0         0.0                 0                0                              3
                      2      0               0                        0              0         0.0                 0                0                              3
                      3      0               0                        0              0         0.0                 0                0                              3
                      4      0               0                        0              0         0.0                 0                0                              3
                      5      0               0                        0              0         0.0                 0                0                              3
                                                                                                                                                                  ..
949628          2018  12     0               0                        0              0         0.0                 0                0                              2
960050          2018  12     0               0                        0              0         0.0                 0                0                              2
971370          2018  12     0               0                        0              0         0.0                 0                0                              2
988392          2018  12     0               0                        0              0         0.0                 0                0                              2
989528          2018  12     0               0                        0              0         0.0                 0                0                              2
Name: count, Length: 1848, dtype: int64

In [12]:
#El método columns nos devuelve una lista con los nombres de las columnas del df_1
df_1.columns

Index(['Loyalty Number', 'Year', 'Month', 'Flights Booked',
       'Flights with Companions', 'Total Flights', 'Distance',
       'Points Accumulated', 'Points Redeemed', 'Dollar Cost Points Redeemed'],
      dtype='str')

En este dataframe no es necesasrio aplicar filtros para identificar valores únicos porque todos mantienen integridad estructural. La única columna que podía tener alguna problemática es 'Month' al ser 12 valores únicos (uno por mes). Ha sido inspeccionada y no hay ningún error.

In [ ]:
#El método isna nos devuelve un booleano indicando si cada valor es nulo o no. El método sum nos devuelve el número total de valores nulos en cada columna.
df_1.isna().sum()
#Vemos que en el df_1 no hay valores nulos, no hace falta decidir qué hacer con ellos ni obtener el porcentaje.

Loyalty Number                 0
Year                           0
Month                          0
Flights Booked                 0
Flights with Companions        0
Total Flights                  0
Distance                       0
Points Accumulated             0
Points Redeemed                0
Dollar Cost Points Redeemed    0
dtype: int64

In [ ]:
#El método sample nos devuelve una muestra aleatoria de filas del dataframe
df_2.sample(5)

,Loyalty Number,Country,Province,City,Postal Code,Gender,Education,Salary,Marital Status,Loyalty Card,CLV,Enrollment Type,Enrollment Year,Enrollment Month,Cancellation Year,Cancellation Month
2307,891516,Canada,Ontario,Sudbury,M5V 1G5,Male,Bachelor,104870.0,Married,Aurora,7901.43,Standard,2018,6,NaN,NaN
3672,487727,Canada,British Columbia,Whistler,V6T 1Y8,Female,Bachelor,97770.0,Single,Aurora,16304.30,Standard,2016,3,NaN,NaN
3207,694512,Canada,Nova Scotia,Halifax,B3J 9S2,Female,Bachelor,53481.0,Married,Aurora,11064.29,Standard,2013,5,NaN,NaN
12604,378267,Canada,Ontario,Toronto,M2P 4F6,Male,College,NaN,Married,Star,4135.78,Standard,2012,12,NaN,NaN
4322,955773,Canada,British Columbia,Vancouver,V6E 3D9,Male,Bachelor,87992.0,Married,Star,5226.29,2018 Promotion,2018,2,NaN,NaN

In [15]:
#El método info nos devuelve un resumen de la información del dataframe, incluyendo el número de filas, el número de columnas, 
#el tipo de datos de cada columna y el número de valores no nulos en cada columna.
#Vemos que hay 16 columnas, 9 de ellas son de tipo string, 3 de tipo int64 y 4 de tipo float64. 
df_2.info()
#Vemos que este método nos indica que no hay nulos, pero la realidad es que sí hay solo que están representados por una máscara.

<class 'pandas.DataFrame'>
RangeIndex: 16737 entries, 0 to 16736
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Loyalty Number      16737 non-null  int64
 1   Country             16737 non-null  str
 2   Province            16737 non-null  str
 3   City                16737 non-null  str
 4   Postal Code         16737 non-null  str
 5   Gender              16737 non-null  str
 6   Education           16737 non-null  str
 7   Salary              12499 non-null  float64
 8   Marital Status      16737 non-null  str
 9   Loyalty Card        16737 non-null  str
 10  CLV                 16737 non-null  float64
 11  Enrollment Type     16737 non-null  str
 12  Enrollment Year     16737 non-null  int64
 13  Enrollment Month    16737 non-null  int64
 14  Cancellation Year   2067 non-null   float64
 15  Cancellation Month  2067 non-null   float64
dtypes: float64(4), int64(3), str(9)
memory usage: 2.0 MB

In [16]:
#En este caso el método describe no es suficiente porque las columnas son numéricas y categóricas 
df_2.describe().T

,count,mean,std,min,25%,50%,75%,max
Loyalty Number,16737.0,549735.880445,258912.132453,100018.00,326603.00,550434.00,772019.00,999986.00
Salary,12499.0,79245.609409,35008.297285,-58486.00,59246.50,73455.00,88517.50,407228.00
CLV,16737.0,7988.896536,6860.982280,1898.01,3980.84,5780.18,8940.58,83325.38
Enrollment Year,16737.0,2015.253211,1.979111,2012.00,2014.00,2015.00,2017.00,2018.00
Enrollment Month,16737.0,6.669116,3.398958,1.00,4.00,7.00,10.00,12.00
Cancellation Year,2067.0,2016.503145,1.380743,2013.00,2016.00,2017.00,2018.00,2018.00
Cancellation Month,2067.0,6.962748,3.455297,1.00,4.00,7.00,10.00,12.00

In [18]:
#Añadimos el parámetro include='str' para obtener un resumen estadístico de las columnas de tipo string del df_2
df_2.describe(include='str').T

                 count unique       top   freq
Country          16737      1    Canada  16737
Province         16737     11   Ontario   5404
City             16737     29   Toronto   3351
Postal Code      16737     55   V6E 3D9    911
Gender           16737      2    Female   8410
Education        16737      5  Bachelor  10475
Marital Status   16737      3   Married   9735
Loyalty Card     16737      3      Star   7637
Enrollment Type  16737      2  Standard  15766

In [ ]:
#El método shape nos devuelve el número de filas y columnas del df_2
print(f"El número de filas que tenemos es {df_2.shape[0]}, y el número de columnas es {df_2.shape[1]}")

El número de filas que tenemos es 16737, y el número de columnas es 16

In [ ]:
#No hay filas duplicadas en el df_2
df_2.duplicated().sum()

np.int64(0)

In [19]:
df_2.columns

Index(['Loyalty Number', 'Country', 'Province', 'City', 'Postal Code',
       'Gender', 'Education', 'Salary', 'Marital Status', 'Loyalty Card',
       'CLV', 'Enrollment Type', 'Enrollment Year', 'Enrollment Month',
       'Cancellation Year', 'Cancellation Month'],
      dtype='str')

In [ ]:
#El método unique nos devuelve una lista de los valores únicos de la columna "Country" del df_2
df_2["Country"].unique()
#Observamos que solo hay un valor - Canada - posible drop?

<StringArray>
['Canada']
Length: 1, dtype: str

Después de aplicar el método .unique al resto de columnas, la columna country es la única que aporta información relevante.

In [ ]:
#El método isna nos devuelve un booleano indicando si cada valor es nulo o no. El método sum nos devuelve el número total de valores nulos en cada columna.
df_2.isna().sum()

Loyalty Number            0
Country                   0
Province                  0
City                      0
Postal Code               0
Gender                    0
Education                 0
Salary                 4238
Marital Status            0
Loyalty Card              0
CLV                       0
Enrollment Type           0
Enrollment Year           0
Enrollment Month          0
Cancellation Year     14670
Cancellation Month    14670
dtype: int64

In [ ]:
#Obtenemos el porcentaje de valores nulos en cada columna del df_2
df_2.isna().sum()/df_2.shape[0]*100

Loyalty Number         0.000000
Country                0.000000
Province               0.000000
City                   0.000000
Postal Code            0.000000
Gender                 0.000000
Education              0.000000
Salary                25.321145
Marital Status         0.000000
Loyalty Card           0.000000
CLV                    0.000000
Enrollment Type        0.000000
Enrollment Year        0.000000
Enrollment Month       0.000000
Cancellation Year     87.650117
Cancellation Month    87.650117
dtype: float64